services:
  web:
    image: nginx           
    ports:
      - "8080:80"             
    volumes:
      - ./html:/usr/share/nginx/html 
    depends_on:
      - db
    networks:
      - app-net        
  db:
    image: mysql      
    environment:
      MYSQL_ROOT_PASSWORD: example    
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - app-net      
volumes:
  db-data:
networks:
  app-net:              
    driver: bridge 
